name: Build Debian package

uses: dawidd6/action-debian-package@v1.6.0
  
with:
    # Target CPU architecture (amd64, arm64, arm, ...)
    cpu_architecture: # optional, default is amd64
    # Directory where Debian sources are, relative to workspace
    source_directory: # optional, default is ./
    # Directory where build artifacts will be placed, relative to workspace
    artifacts_directory: # optional, default is ./
    # OS distribution name, value from `debian/changelog` is used if not defined
    os_distribution: # optional
    # Command line parameters provided to 'lintian'
    lintian_opts: # optional, default is 
    # Run lintian checks
    lintian_run: # optional
