name: Build DEB package
  # You may pin to the exact commit or the version.
  # uses: DevChall-by-SDCY-and-VXM/debian-buildpackage-template@66fa246e5413db3c4e145307f176ba8aa82546aa
  uses: DevChall-by-SDCY-and-VXM/debian-buildpackage-template@v0.0.13
  with:
    distro: debian:latest
    arch: amd64

    build_arguments: # default is -b
    build_options: # default is 
    build_profiles: # default is 
    gpg_signing_key: # optional
    package_name: # optional
    package_version: # optional
    package_maintainer: christian.lorenz@gromeck.de
    package_class: s 
    package_generate_orig: # optional
