name: Build Debian package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Debian package dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/deb
        key: ${{ runner.os }}-deb-${{ hashFiles('**/debian/control') }}
        restore-keys: |
          ${{ runner.os }}-deb-

    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1.6.0
      with:
        cpu_architecture: amd64
        source_directory: ./
        artifacts_directory: ./artifacts
        os_distribution: debian
        lintian_opts: --info --display-info
        lintian_run: true

    - name: Upload Debian package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: ./artifacts/*.deb
